// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_IlR-5QVx_rju00lcrUi0Y5FMjt_qlio',
    appId: '1:868460518196:web:af2f267be52da4f1e66361',
    messagingSenderId: '868460518196',
    projectId: 'client-project-da733',
    authDomain: 'client-project-da733.firebaseapp.com',
    storageBucket: 'client-project-da733.firebasestorage.app',
    measurementId: 'G-SV17YKG8M1',
    databaseURL: 'https://client-project-da733-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHXi99WryUEUrdnTePik59Gjtl404q4yc',
    appId: '1:868460518196:android:b4a0373772000cbae66361',
    messagingSenderId: '868460518196',
    projectId: 'client-project-da733',
    storageBucket: 'client-project-da733.firebasestorage.app',
    databaseURL: 'https://client-project-da733-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPpKGi36e6lF_WBrLKw17W6TAsyuF4SnQ',
    appId: '1:868460518196:ios:cb4fe7f35a44c2fce66361',
    messagingSenderId: '868460518196',
    projectId: 'client-project-da733',
    storageBucket: 'client-project-da733.firebasestorage.app',
    iosBundleId: 'com.example.firebasepractice',
    databaseURL: 'https://client-project-da733-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPpKGi36e6lF_WBrLKw17W6TAsyuF4SnQ',
    appId: '1:868460518196:ios:cb4fe7f35a44c2fce66361',
    messagingSenderId: '868460518196',
    projectId: 'client-project-da733',
    storageBucket: 'client-project-da733.firebasestorage.app',
    iosBundleId: 'com.example.firebasepractice',
    databaseURL: 'https://client-project-da733-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_IlR-5QVx_rju00lcrUi0Y5FMjt_qlio',
    appId: '1:868460518196:web:395b774c757f4902e66361',
    messagingSenderId: '868460518196',
    projectId: 'client-project-da733',
    authDomain: 'client-project-da733.firebaseapp.com',
    storageBucket: 'client-project-da733.firebasestorage.app',
    measurementId: 'G-6V2V95JRCP',
    databaseURL: 'https://client-project-da733-default-rtdb.firebaseio.com/'
  );
}
